dist: trusty
language: java
jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./gradlew clean build

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  #SOURCE SERVICE
  - export SOURCE_SERVICE=michaelilyin/openshift-test-source-service
  - docker build -t $SOURCE_SERVICE:$COMMIT ./source-service
  - docker tag $SOURCE_SERVICE:$COMMIT $SOURCE_SERVICE:$TAG
  - docker push $SOURCE_SERVICE:$TAG

  #API SERVICE
  - export API_SERVICE=michaelilyin/openshift-test-api-service
  - docker build -t $API_SERVICE:$COMMIT ./api-service
  - docker tag $API_SERVICE:$COMMIT $API_SERVICE:$TAG
  - docker push $API_SERVICE:$TAG

  - curl https://github.com/openshift/origin/releases/download/v1.5.0-alpha.3/openshift-origin-client-tools-v1.5.0-alpha.3-cf7e336-linux-64bit.tar.gz oc-cli.tar.gz
  - tar -xf oc-cli.tar.gz
  - export PATH=$PATH:`pwd`/oc-cli
  - ./deploy.sh
