version: '2.1'
services:
  demo:
    build:
      context: "./api-service"
    ports:
      - "8080:8080"
    environment:
      - source_service=http://source:8080/source-service-1.0-SNAPSHOT
    links:
      - source
  source:
    build:
      context: "./source-service"
